import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { StrictMode } from "react";

const roboto = Roboto({ weight: "700", style: "normal", subsets: ["latin"] });

// TODO: fix metadata
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html className="overscroll-none" lang="en">
            <body
                className={`relative overscroll-none text-white ${roboto.className}`}
            >
                <StrictMode>{children}</StrictMode>
            </body>
        </html>
    );
}
